package com.company.enums;

public enum MedicineKategory {
    VAKSINA, ANALGESIC, ANTIHISTAMINE, ANTACID, ANTIBIOTIC, ANTI_INFLAMMATORY, HORMONE, STIMULANT, ANTI_ANXIETY, BRONCHODILATOR, SEDATIVE

}
